[tool.black]
line-length = 88
skip-string-normalization = true
target-version = ['py39']

[tool.ruff]
line-length = 88
exclude = [".venv", "migrations", "test", "request"]

[tool.ruff.lint]
ignore = ["E501", "F401", "F811"]

[tool.isort]
profile = "black"
lines_between_sections = 0